# Generated by Django 5.0.6 on 2026-08-29 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_time', models.DateTimeField()),
                ('reason_for_visit', models.CharField(max_length=255)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('note_text', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationNoteAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_note_text', models.TextField(blank=True)),
                ('previous_diagnosis', models.TextField(blank=True)),
                ('previous_plan', models.TextField(blank=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='clinical.consultationnote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_time', models.DateTimeField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('sao2', models.PositiveIntegerField(blank=True, null=True)),
                ('glucose_level', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('glucose_time_of_day', models.CharField(blank=True, max_length=20)),
                ('glucose_fasting', models.BooleanField(blank=True, null=True)),
                ('bp_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('bp_extremity', models.CharField(blank=True, max_length=30)),
                ('bp_position', models.CharField(blank=True, max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
    ]
