# Generated by Django 5.0.6 on 2026-09-03 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0002_patient_file_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField()),
                ('complaint', models.CharField(blank=True, max_length=255)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='patients.patient')),
                ('vitals', models.ForeignKey(blank=True, help_text='The reading this note was taken alongside, when there was one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes', to='clinical.vitals')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
