# Generated by Django 5.0.6 on 2026-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_nursingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationnote',
            name='eye_examination',
            field=models.JSONField(blank=True, help_text='Structured eye examination (see clinical/eye_exam.py). Empty on general notes.', null=True),
        ),
        migrations.AddField(
            model_name='consultationnoteamendment',
            name='previous_eye_examination',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
