# Generated by Django 5.0.6 on 2026-09-16 10:45

"""
The note's amendment trail, completed.

`ConsultationNoteAmendment` already archived what a note said before it was
corrected — `note_text`, `diagnosis`, `plan` and the eye examination. Two of
the note's own fields were missing from that snapshot (`reason_for_visit`,
`chief_complaint`), so an amendment that changed either left no record of what
they had been; and there was nowhere to say *why* the record was changed,
which for a medical record is part of the record.

Four additive, nullable-or-blank columns. Nothing is backfilled and nothing
existing is rewritten: an amendment written before this keeps blank values,
which reads correctly as "this trail predates these columns". `reason` is
`blank=True` at the database for that reason alone — the API requires it on
every new amendment.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_consultation_note_eye_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationnoteamendment',
            name='detail',
            field=models.TextField(blank=True, help_text="What was corrected, in the amender's words."),
        ),
        migrations.AddField(
            model_name='consultationnoteamendment',
            name='previous_chief_complaint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultationnoteamendment',
            name='previous_reason_for_visit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultationnoteamendment',
            name='reason',
            field=models.CharField(blank=True, choices=[('correction', 'Correction of error'), ('additional_information', 'Additional clinical information'), ('clarification', 'Clarification'), ('documentation', 'Documentation correction'), ('other', 'Other')], max_length=40),
        ),
    ]
