# Generated by Django 5.0.6 on 2026-09-05 16:00

from django.db import migrations, models

# The categories the application actually raises. Seeded switched on, so
# behaviour is unchanged the moment this migration runs — the rows exist to
# be turned *off* by a hospital that wants less noise.
CATEGORIES = [
    ("clinical", "Results, vitals and chart activity. Cannot be switched off."),
    ("routing", "Referrals, hand-offs and queue movements."),
    ("pharmacy", "New prescriptions and dispensing."),
    ("billing", "Charges raised and money taken."),
    ("general", "Anything else."),
]


def seed(apps, schema_editor):
    HospitalSettings = apps.get_model("core", "HospitalSettings")
    NotificationSetting = apps.get_model("core", "NotificationSetting")
    if not HospitalSettings.objects.exists():
        HospitalSettings.objects.create()
    for category, description in CATEGORIES:
        NotificationSetting.objects.get_or_create(
            category=category, defaults={"is_enabled": True, "description": description})


def unseed(apps, schema_editor):
    apps.get_model("core", "NotificationSetting").objects.all().delete()
    apps.get_model("core", "HospitalSettings").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repoint_stale_notification_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='NMHS', max_length=120)),
                ('full_name', models.CharField(default='Ngozi Maternity and Hospital Services', max_length=200)),
                ('address', models.CharField(default='Aba, Abia State', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('expiry_warning_days', models.PositiveIntegerField(default=30, help_text='A batch this close to its expiry date is flagged on the stock screens.')),
                ('vitals_wait_alert_minutes', models.PositiveIntegerField(default=30, help_text='How long a patient may wait for vitals before the nursing dashboard says so.')),
                ('unpaid_charge_alert_hours', models.PositiveIntegerField(default=2, help_text='A charge raised this long ago and still unpaid is flagged to the cash desk.')),
            ],
            options={
                'verbose_name': 'hospital settings',
                'verbose_name_plural': 'hospital settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('clinical', 'Clinical — results, vitals, chart activity'), ('routing', 'Routing — referrals and hand-offs'), ('pharmacy', 'Pharmacy — prescriptions and dispensing'), ('billing', 'Billing — charges raised and money taken'), ('general', 'General')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
