# Generated by Django 5.0.6 on 2026-09-14 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_discount_limit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The largest sum a cashier may take off on their own. 0 means no ceiling of its own — the percentage limit still applies.', max_digits=12),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_discount_limit_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='The largest percentage a cashier may give on their own. Above this needs an authorised approval. 100 means no approval is ever needed.', max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_discount_presets',
            field=models.CharField(blank=True, default='5,10,15,20,25', help_text='The percentage buttons the discount dialog offers, comma separated. The cashier can always type another value, within the limits above.', max_length=120),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_discount_reasons',
            field=models.CharField(blank=True, default='Staff discount,Loyal customer,Hospital concession,Management approval,Promotional discount', help_text='The reasons the discount dialog offers, comma separated. A reason is always required; a cashier may write their own.', max_length=400),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_discount_types',
            field=models.CharField(choices=[('both', 'Percentage and fixed amount'), ('percent', 'Percentage only'), ('amount', 'Fixed amount only')], default='both', help_text='Which kinds of discount the till offers.', max_length=10),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_discounts_enabled',
            field=models.BooleanField(default=True, help_text='Whether the pharmacy till may give discounts at all. Off refuses every one, whatever the role.'),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The largest sum anybody may take off, approval or not. 0 means no ceiling.', max_digits=12),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='pos_max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='The largest percentage anybody may give, approval or not.', max_digits=5),
        ),
    ]
