# Generated by Django 5.0.6 on 2026-09-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-admitted_at']},
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['ward__name', 'number']},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['name']},
        ),
    ]
