# Generated by Django 5.0.6 on 2026-09-02 21:01

from django.db import migrations, models


def backfill_scheduled_to_queued(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    Appointment.objects.filter(status="scheduled").update(status="queued")


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_scheduled_to_queued, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
