# Generated by Django 5.0.6 on 2026-09-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_alter_appointment_end_time_and_more'),
        ('billing', '0020_billingitem_is_appointment_service'),
        ('departments', '0003_seed_clinical_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='billing.charge'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='departments.department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='billing.billingitem'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
