# Generated by Django 5.0.6 on 2026-09-21 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_charge_appointment_department_and_more'),
        ('billing', '0021_seed_appointment_services'),
        ('departments', '0003_seed_clinical_departments'),
        ('patients', '0009_patient_uuid_and_patient_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'accepted', 'in_progress'])), fields=('patient', 'doctor'), name='one_open_appointment_per_patient_and_provider'),
        ),
    ]
