# Generated by Django 5.0.6 on 2026-09-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_one_open_appointment_per_patient_and_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='Order-time snapshot of every service booked: key, name, fee and charge.'),
        ),
    ]
