# Generated by Django 5.0.6 on 2026-09-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_seed_clinical_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_appointment_available',
            field=models.BooleanField(default=False, help_text='When enabled, Reception can select this department when booking an appointment. It does not affect anything else the department does.', verbose_name='available for appointments'),
        ),
    ]
