# Generated by Django 5.0.6 on 2026-09-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicaltest_file_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'ordering': ['-test_date', '-created_at']},
        ),
    ]
