# Generated by Django 5.0.6 on 2026-09-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_medicaltest_options'),
        ('workflow', '0004_patientroute_result_patientroute_result_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='source_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_tests', to='workflow.patientroute'),
        ),
    ]
