# Generated by Django 5.0.6 on 2026-09-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicaltest_source_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
