# Generated by Django 5.0.6 on 2026-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientroute',
            name='purpose',
            field=models.CharField(choices=[('vitals', 'Vitals'), ('consultation', 'Consultation'), ('procedure', 'Procedure'), ('investigation', 'Investigation'), ('other', 'Other')], default='consultation', max_length=20),
        ),
    ]
