# Generated by Django 5.0.6 on 2026-09-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_patientroute_result_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientroute',
            name='purpose',
            field=models.CharField(choices=[('vitals', 'Vitals'), ('consultation', 'Consultation'), ('procedure', 'Procedure'), ('laboratory', 'Laboratory'), ('ultrasound', 'Ultrasound / Imaging'), ('eye', 'Eye clinic'), ('maternity', 'Maternity'), ('investigation', 'Investigation'), ('other', 'Other')], default='consultation', max_length=20),
        ),
    ]
