# Generated by Django 5.0.6 on 2026-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sensitive_record_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('reception', 'Reception'), ('pharmacist', 'Pharmacist'), ('laboratory', 'Laboratory Scientist'), ('radiology', 'Radiology Staff'), ('optometrist', 'Optometrist'), ('surgeon', 'Surgeon'), ('cashier', 'Billing Officer / Cashier'), ('ward_manager', 'Ward Manager'), ('inventory_manager', 'Inventory Manager'), ('accountant', 'Accountant'), ('executive', 'Management / Executive'), ('custom', 'Custom role')], max_length=20),
        ),
    ]
