# Generated by Django 5.0.6 on 2026-08-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('reception', 'Reception'), ('pharmacist', 'Pharmacist'), ('laboratory', 'Laboratory Scientist'), ('radiology', 'Radiology Staff'), ('optometrist', 'Optometrist'), ('ophthalmologist', 'Ophthalmologist / Eye Doctor'), ('surgeon', 'Surgeon'), ('anesthetist', 'Anesthetist'), ('cashier', 'Billing Officer / Cashier'), ('ward_manager', 'Ward Manager'), ('records_officer', 'Records Officer'), ('inventory_manager', 'Inventory Manager'), ('accountant', 'Accountant'), ('executive', 'Management / Executive'), ('custom', 'Custom role')], max_length=20),
        ),
    ]
