# Generated by Django 5.0.6 on 2026-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_staff_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_discount_authorized',
            field=models.BooleanField(default=False, help_text='Allows this staff member to apply pharmacy POS discounts within the existing configured limits. This does not grant discount approval authority. It only has effect for someone who works the POS till.', verbose_name='POS discount authorized'),
        ),
    ]
