# Generated by Django 5.0.6 on 2026-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_pos_discount_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('maternity_nurse', 'Maternity'), ('reception', 'Reception'), ('pharmacist', 'Pharmacist'), ('laboratory', 'Laboratory Scientist'), ('radiology', 'Radiology Staff'), ('optometrist', 'Optometrist'), ('ophthalmologist', 'Ophthalmologist / Eye Doctor'), ('surgeon', 'Surgeon'), ('anesthetist', 'Anesthetist'), ('cashier', 'Billing Officer / Cashier'), ('ward_manager', 'Ward Manager'), ('records_officer', 'Records Officer'), ('inventory_manager', 'Inventory Manager'), ('accountant', 'Accountant'), ('executive', 'Management / Executive'), ('custom', 'Custom role')], max_length=20),
        ),
    ]
