# Generated by Django 5.0.6 on 2026-09-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0009_patient_uuid_and_patient_number'),
        ('workflow', '0006_patientroute_result_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityVisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_booking', models.BooleanField(default=False, help_text="The visit that opens a pregnancy's record and takes the obstetric history.", verbose_name='first ANC / booking visit')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(default=1)),
                ('lmp', models.DateField(blank=True, null=True, verbose_name='last menstrual period')),
                ('edd', models.DateField(blank=True, null=True, verbose_name='estimated delivery date')),
                ('gravida', models.PositiveSmallIntegerField(blank=True, help_text='Total pregnancies including this one.', null=True)),
                ('para', models.PositiveSmallIntegerField(blank=True, help_text='Births after 28 weeks.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('ended', 'Ended')], default='active', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('miscarriage', 'Miscarriage'), ('stillbirth', 'Stillbirth'), ('termination', 'Termination'), ('transferred', 'Transferred out'), ('lost_to_follow_up', 'Lost to follow-up')], max_length=20)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancies_opened', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'pregnancies',
                'ordering': ['-number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaternityEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('seen_on', models.DateField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_encounters', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_encounters_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_encounters', to='workflow.visit')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='maternity.maternityvisittype')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='maternity.pregnancy')),
            ],
            options={
                'ordering': ['-seen_on', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active'])), fields=('patient',), name='one_active_pregnancy_per_patient'),
        ),
    ]
