# Generated by Django 5.0.6 on 2026-09-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_amendment_reason_and_full_snapshot'),
        ('inpatient', '0004_discharge_reference_and_condition'),
        ('maternity', '0002_seed_visit_types'),
        ('patients', '0009_patient_uuid_and_patient_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('delivery_type', 'Delivery type'), ('delivery_outcome', 'Delivery outcome'), ('complication', 'Complication'), ('newborn_status', 'Newborn status'), ('mother_condition', "Mother's condition"), ('family_planning', 'Family planning method')], max_length=30)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Newborn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(blank=True, help_text='Often not chosen for days. Left blank rather than guessed.', max_length=120)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Ambiguous')], max_length=1)),
                ('birth_weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('apgar_1_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apgar_5_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apgar_10_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('congenital_abnormalities', models.TextField(blank=True)),
                ('admitted_to_nursery', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['delivery', 'birth_order'],
            },
        ),
        migrations.CreateModel(
            name='PostpartumVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_at', models.DateTimeField()),
                ('bleeding', models.CharField(blank=True, max_length=200)),
                ('wound_condition', models.CharField(blank=True, max_length=200)),
                ('breastfeeding_established', models.BooleanField(blank=True, null=True)),
                ('baby_feeding', models.CharField(blank=True, max_length=200)),
                ('discharge_advice', models.TextField(blank=True)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
        migrations.CreateModel(
            name='LabourEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onset', models.CharField(choices=[('spontaneous', 'Spontaneous'), ('induced', 'Induced'), ('elective_caesarean', 'Elective caesarean'), ('emergency', 'Emergency')], default='spontaneous', max_length=30)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('delivered', 'Delivered'), ('transferred', 'Transferred out'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('stage', models.CharField(choices=[('latent', 'Latent first stage'), ('active', 'Active first stage'), ('second', 'Second stage'), ('third', 'Third stage'), ('fourth', 'Fourth stage (immediate recovery)')], default='latent', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_episodes', to='inpatient.admission')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_episodes_opened', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_episodes', to='maternity.pregnancy')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField()),
                ('estimated_blood_loss_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('placenta_complete', models.BooleanField(blank=True, null=True)),
                ('placenta_notes', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_attended', to=settings.AUTH_USER_MODEL)),
                ('midwife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_as_midwife', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_recorded', to=settings.AUTH_USER_MODEL)),
                ('labour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='maternity.labourepisode')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabourObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_at', models.DateTimeField()),
                ('cervical_dilation_cm', models.PositiveSmallIntegerField(blank=True, help_text='0–10 cm.', null=True)),
                ('contractions_per_10min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contraction_duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fetal_heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='Beats per minute.', null=True)),
                ('membranes', models.CharField(blank=True, choices=[('intact', 'Intact'), ('ruptured_clear', 'Ruptured — clear'), ('ruptured_meconium', 'Ruptured — meconium'), ('ruptured_blood', 'Ruptured — blood stained')], max_length=30)),
                ('maternal_condition', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='maternity.labourepisode')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_observations', to=settings.AUTH_USER_MODEL)),
                ('vitals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_observations', to='clinical.vitals')),
            ],
            options={
                'ordering': ['observed_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='maternityoption',
            constraint=models.UniqueConstraint(fields=('kind', 'code'), name='unique_maternity_option'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='complications',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'complication'}, related_name='deliveries_with_complication', to='maternity.maternityoption'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.ForeignKey(limit_choices_to={'kind': 'delivery_type'}, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_of_type', to='maternity.maternityoption'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='maternal_condition',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'mother_condition'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_with_maternal_condition', to='maternity.maternityoption'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='outcome',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'delivery_outcome'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_with_outcome', to='maternity.maternityoption'),
        ),
        migrations.AddField(
            model_name='newborn',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newborns', to='maternity.delivery'),
        ),
        migrations.AddField(
            model_name='newborn',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Set once the baby is registered as a patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='newborn',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newborns_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newborn',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'newborn_status'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newborns_with_status', to='maternity.maternityoption'),
        ),
        migrations.AddField(
            model_name='postpartumvisit',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_visits', to='maternity.delivery'),
        ),
        migrations.AddField(
            model_name='postpartumvisit',
            name='family_planning',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'family_planning'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postpartum_with_family_planning', to='maternity.maternityoption'),
        ),
        migrations.AddField(
            model_name='postpartumvisit',
            name='mother_condition',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'mother_condition'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postpartum_with_condition', to='maternity.maternityoption'),
        ),
        migrations.AddField(
            model_name='postpartumvisit',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postpartum_visits_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postpartumvisit',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postpartum_visits', to='clinical.vitals'),
        ),
        migrations.AddConstraint(
            model_name='labourepisode',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('pregnancy',), name='one_labour_in_progress_per_pregnancy'),
        ),
        migrations.AddConstraint(
            model_name='newborn',
            constraint=models.UniqueConstraint(fields=('delivery', 'birth_order'), name='unique_birth_order_per_delivery'),
        ),
    ]
