# Generated by Django 5.0.6 on 2026-09-25 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maternity', '0004_seed_maternity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, choices=[('typo', 'Typing or data-entry error'), ('wrong_value', 'Wrong value recorded'), ('incomplete', 'Record was incomplete'), ('clarification', 'Clarifying what was recorded'), ('other', 'Other (explained below)')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('previous', models.JSONField(blank=True, default=dict)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternity_amendments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='maternity_m_content_bd89ad_idx')],
            },
        ),
    ]
