# Generated by Django 5.0.6 on 2026-09-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingitem_delete_cardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(choices=[('front_desk', 'Front desk'), ('pharmacy', 'Pharmacy'), ('cashier', 'Cashier')], default='front_desk', max_length=20),
        ),
    ]
