# Generated by Django 5.0.6 on 2026-09-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
