# Generated by Django 5.0.6 on 2026-09-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_backfill_charge_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='amount_discounted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
