# Generated by Django 5.0.6 on 2026-09-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_charge_amount_discounted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patientledger',
            options={'ordering': ['patient__last_name', 'patient__first_name']},
        ),
    ]
