# Generated by Django 5.0.6 on 2026-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_adjustment_options_alter_patientledger_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation Fee'), ('card', 'Card'), ('laboratory', 'Laboratory'), ('ultrasound', 'Ultrasound / Imaging'), ('eye', 'Eye clinic'), ('procedure', 'Procedure'), ('other', 'Other')], default='card', max_length=20),
        ),
    ]
