# Generated by Django 5.0.6 on 2026-09-07 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_backfill_waived_amounts'),
        ('departments', '0001_initial'),
        ('patients', '0009_patient_uuid_and_patient_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['kind', 'created_at'], name='billing_adj_kind_e40675_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['created_at'], name='billing_cha_created_636544_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['source_type', 'created_at'], name='billing_cha_source__ffb02e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='billing_pay_created_a6e2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'created_at'], name='billing_pay_method_5b2ada_idx'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.charge'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['charge', 'payment'], name='billing_pay_charge__72b102_idx'),
        ),
    ]
