# Generated by Django 5.0.6 on 2026-09-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_backfill_payment_allocations'),
        ('departments', '0002_seed_revenue_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
    ]
