# Generated by Django 5.0.6 on 2026-09-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_charge_cancellation'),
        ('patients', '0009_patient_uuid_and_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='amount_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='kind',
            field=models.CharField(choices=[('discount', 'Discount'), ('waiver', 'Waiver'), ('refund', 'Refund'), ('return', 'Goods returned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='patients.patient'),
        ),
    ]
