# Generated by Django 5.0.6 on 2026-09-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_seed_ultrasound_examinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='is_appointment_service',
            field=models.BooleanField(default=False, help_text='Offer this service on the Appointments booking form. The department and the eligible providers follow from the category; the fee is the price above.', verbose_name='bookable as an appointment'),
        ),
    ]
