import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import api from "../api/client";

const TONES = { blue: "from-blue-500 to-brand-600", violet: "from-violet-500 to-fuchsia-600", green: "from-emerald-500 to-teal-600", amber: "from-amber-400 to-orange-500", red: "from-rose-500 to-red-600", slate: "from-slate-600 to-slate-800" };
const formatValue = (card) => card.format === "currency" ? new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(card.value ?? 0) : card.value ?? 0;

export default function Dashboard() {
  const { data, isLoading, isError, refetch, isFetching } = useQuery({ queryKey: ["dashboard"], queryFn: () => api.get("/dashboard/").then((response) => response.data) });
  if (isLoading) return <div className="p-6 text-slate-500">Loading your workspace…</div>;
  if (isError) return <div className="p-6"><p className="text-red-700">Could not load the dashboard.</p><button onClick={refetch} className="mt-3 rounded bg-slate-900 px-3 py-2 text-sm text-white">Try again</button></div>;
  return <div className="max-w-7xl mx-auto p-5 md:p-8 space-y-7">
    <div className="overflow-hidden rounded-3xl bg-brand-950 px-6 py-7 text-white shadow-xl shadow-brand-900/10 md:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm text-brand-300">{data.today}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{data.is_admin ? "Hospital operations" : `My ${data.role} workspace`}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">{data.is_admin ? "A live view of care delivery, finances, capacity, and operational activity." : "Your live work queue, patient updates, and department tasks."}</p></div><button onClick={refetch} className="rounded-xl bg-white/10 px-4 py-2.5 text-sm font-medium ring-1 ring-white/20 transition hover:bg-white/20">{isFetching ? "Refreshing…" : "Refresh dashboard"}</button></div></div>
    <section className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{data.cards.map((card) => <Link key={card.label} to={card.href} className={`group relative overflow-hidden rounded-2xl bg-gradient-to-br p-[1px] shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg ${TONES[card.tone] || TONES.slate}`}><div className="h-full rounded-2xl bg-white p-5"><p className="text-sm font-medium text-slate-500">{card.label}</p><p className="mt-3 text-2xl font-bold tracking-tight text-slate-900">{formatValue(card)}</p><p className="mt-4 text-xs font-medium text-slate-600 group-hover:text-brand-600">View details →</p></div></Link>)}</section>
    {data.alerts?.length > 0 && <section className="rounded-2xl border border-amber-200 bg-gradient-to-r from-amber-50 to-orange-50 p-5"><h2 className="font-semibold text-amber-950">Attention needed</h2><div className="mt-3 grid gap-2">{data.alerts.map((alert) => <Link key={alert.label} to={alert.href} className="rounded-lg bg-white/70 px-3 py-2 text-sm text-amber-900 transition hover:bg-white hover:shadow-sm">{alert.label} <span className="float-right">→</span></Link>)}</div></section>}
    <div className="grid lg:grid-cols-5 gap-6"><section className="lg:col-span-3 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-semibold">{data.is_admin ? "Active hospital queues" : "My active queue"}</h2><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-medium text-brand-700">Live</span></div>{data.tasks.length ? <div className="divide-y divide-slate-100">{data.tasks.map((task) => <Link to={task.href ?? "/patients"} key={task.id} className="block px-5 py-4 transition hover:bg-slate-50"><div className="flex justify-between gap-3"><div><p className="font-medium text-slate-800">{task.patient}</p><p className="mt-1 text-sm text-slate-500">{task.purpose ? `${task.purpose} · ` : ""}{task.department} · {task.assigned_to}</p></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs font-medium ${task.priority === "emergency" ? "bg-red-100 text-red-700" : task.priority === "urgent" ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-600"}`}>{task.priority}</span></div></Link>)}</div> : <p className="p-5 text-sm text-slate-500">No active items are assigned to this workspace.</p>}</section><section className="lg:col-span-2 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-semibold">Recent activity</h2></div>{data.recent_activity.length ? <div className="divide-y divide-slate-100">{data.recent_activity.map((event) => <div className="px-5 py-3.5" key={event.id}><p className="text-sm font-medium text-slate-700">{event.action}</p>{event.actor && <p className="mt-0.5 text-xs text-slate-500">{event.actor}</p>}<p className="mt-1 text-xs text-slate-600">{new Date(event.created_at).toLocaleString()}</p></div>)}</div> : <p className="p-5 text-sm text-slate-500">No activity has been recorded yet.</p>}</section></div>
  </div>;
}
