# Generated by Django 5.0.6 on 2026-09-03 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0010_seed_service_billing_items'),
        ('departments', '0001_initial'),
        ('patients', '0008_age_value_and_unit'),
        ('workflow', '0004_patientroute_result_patientroute_result_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('group', models.CharField(blank=True, max_length=80)),
                ('result_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('positive_negative', 'Positive / Negative'), ('reactive_nonreactive', 'Reactive / Non-reactive'), ('detected_notdetected', 'Detected / Not detected'), ('normal_abnormal', 'Normal / Abnormal'), ('select', 'Select option')], default='numeric', max_length=25)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('reference_range', models.CharField(blank=True, max_length=120)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('normal_value', models.CharField(blank=True, max_length=120)),
                ('options', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('is_required', models.BooleanField(default=False, help_text='Off by design. A parameter is only filled in when it was measured.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['test', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('collected', 'Sample collected'), ('in_progress', 'In progress'), ('awaiting_verification', 'Awaiting verification'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=25)),
                ('clinical_notes', models.TextField(blank=True)),
                ('specimen_id', models.CharField(blank=True, max_length=40)),
                ('specimen_collected_at', models.DateTimeField(blank=True, null=True)),
                ('lab_comments', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_specimens_collected', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_created', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_entered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_requested', to=settings.AUTH_USER_MODEL)),
                ('route', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order', to='workflow.patientroute')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_verified', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='workflow.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('resulted', 'Resulted'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('comments', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabResultAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_amendments', to=settings.AUTH_USER_MODEL)),
                ('order_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='laboratory.labordertest')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='laboratory.labparameter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('flag', models.CharField(blank=True, choices=[('', '—'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('abnormal', 'Abnormal'), ('critical', 'Critical'), ('positive', 'Positive'), ('negative', 'Negative'), ('reactive', 'Reactive'), ('non_reactive', 'Non-reactive')], default='', max_length=15)),
                ('flag_is_manual', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('unit_at_entry', models.CharField(blank=True, max_length=40)),
                ('reference_at_entry', models.CharField(blank=True, max_length=120)),
                ('order_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='laboratory.labordertest')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labparameter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_values_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_test', 'parameter__display_order', 'parameter_id'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('haematology', 'Haematology'), ('chemistry', 'Chemical Pathology / Clinical Chemistry'), ('microbiology', 'Microbiology'), ('parasitology', 'Parasitology'), ('urinalysis', 'Urinalysis'), ('serology', 'Serology / Immunology'), ('endocrinology', 'Endocrinology / Hormones'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('specimen_type', models.CharField(blank=True, max_length=120)),
                ('container', models.CharField(blank=True, max_length=120)),
                ('turnaround_hours', models.PositiveIntegerField(blank=True, help_text='Roughly how long a result takes, in hours.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('billing_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='billing.billingitem')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='departments.department')),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='labparameter',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='laboratory.labtest'),
        ),
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tests', models.ManyToManyField(blank=True, related_name='panels', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labordertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', '-created_at'], name='laboratory__status_45ff77_idx'),
        ),
        migrations.AddConstraint(
            model_name='labresultvalue',
            constraint=models.UniqueConstraint(fields=('order_test', 'parameter'), name='unique_value_per_parameter'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['category', 'is_active'], name='laboratory__categor_b3cfcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='labparameter',
            constraint=models.UniqueConstraint(fields=('test', 'code'), name='unique_parameter_code_per_test'),
        ),
        migrations.AddConstraint(
            model_name='labordertest',
            constraint=models.UniqueConstraint(fields=('order', 'test'), name='unique_test_per_lab_order'),
        ),
    ]
