# Generated by Django 5.0.6 on 2026-09-03 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_backfill_waived_amounts'),
        ('laboratory', '0002_seed_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labordertest',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order_tests', to='billing.charge'),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='container',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='parameters_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='source',
            field=models.CharField(choices=[('requested', 'Requested by the clinician'), ('laboratory', 'Added by the laboratory')], default='requested', max_length=15),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='test_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='test_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labordertest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labordertest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft — being entered'), ('submitted', 'Submitted for verification'), ('verified', 'Verified / released'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
