# Generated by Django 5.0.6 on 2026-09-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_prescription_cancelled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='route',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('sublingual', 'Sublingual'), ('iv', 'Intravenous (IV)'), ('im', 'Intramuscular (IM)'), ('sc', 'Subcutaneous (SC)'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('nasal', 'Nasal'), ('ophthalmic', 'Eye (ophthalmic)'), ('otic', 'Ear (otic)'), ('rectal', 'Rectal'), ('vaginal', 'Vaginal'), ('other', 'Other')], max_length=20),
        ),
    ]
