# Generated by Django 5.0.6 on 2026-09-28 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_charges(apps, schema_editor):
    """
    Point each historical prescription at the charge that already names it.

    **Links only.** Before this change a charge was raised at dispensing with
    `source_type="prescription"` and `source_id` = the prescription, so the
    relationship already existed as a pair of columns; this writes it into the
    FK where it is exactly one charge. Nothing is created, priced or altered:
    a pending script written before prescriptions were billed keeps no charge
    and no `quoted_amount`, and is billed on request by the counter
    (`POST /prescriptions/<id>/bill/`) rather than by a migration inventing
    its amount.
    """
    Prescription = apps.get_model("pharmacy", "Prescription")
    Charge = apps.get_model("billing", "Charge")
    counts = {}
    for source_id in Charge.objects.filter(source_type="prescription",
                                           source_id__isnull=False).values_list("source_id", flat=True):
        counts[source_id] = counts.get(source_id, 0) + 1
    for prescription in Prescription.objects.filter(charge__isnull=True, pk__in=list(counts)):
        if counts.get(prescription.pk) != 1:
            continue   # ambiguous: leave it for a person, never guess
        charge = Charge.objects.get(source_type="prescription", source_id=prescription.pk)
        if charge.patient_id != prescription.patient_id:
            continue
        Prescription.objects.filter(pk=prescription.pk).update(charge=charge)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_seed_maternity_services'),
        ('inventory', '0009_batch_manual_expiry'),
        ('patients', '0009_patient_uuid_and_patient_number'),
        ('pharmacy', '0003_prescription_directions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='billing.charge'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='client_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quoted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(condition=models.Q(('client_token__isnull', False)), fields=('client_token', 'item'), name='one_line_per_drug_per_submission'),
        ),
        migrations.RunPython(link_existing_charges, migrations.RunPython.noop),
    ]
