# Generated by Django 5.0.6 on 2026-09-11 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

"""
The pharmacy POS: registers, sales with lines and batch pieces, returns.

`sales` existed before this as an unfinished, admin-only pair of tables that
moved no stock and took no payment. Two things about any rows it left behind
are handled here rather than silently:

* **Line discounts on the old `SaleItem` are not dropped quietly.** Those
  columns were a discount approval record. If any row carries one, the
  migration stops and says so — copy them somewhere first.
* **Old sales never read as POS revenue.** They had no payment behind them, so
  they are given a reference and marked `cancelled` (with `cancelled_at` set to
  when they were written). Counting them as completed would put money in the
  POS figures that no `Payment` row, and so no finance report, contains.
"""


def refuse_to_drop_legacy_discounts(apps, schema_editor):
    SaleItem = apps.get_model("sales", "SaleItem")
    carrying = SaleItem.objects.exclude(discount_percent=0).count()
    if carrying:
        raise RuntimeError(
            f"{carrying} legacy sale item(s) carry a discount approval that this migration "
            f"would delete. Export sales_saleitem (discount_percent, discount_reason, "
            f"approved_by) before migrating.")


def settle_legacy_sales(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    for sale in Sale.objects.filter(reference=""):
        Sale.objects.filter(pk=sale.pk).update(
            reference=f"POS-{sale.pk:06d}", status="cancelled", cancelled_at=sale.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_pos_payments_and_returns'),
        ('inventory', '0007_pos_identifiers_strength_and_count_imports'),
        ('patients', '0009_patient_uuid_and_patient_number'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_discount_type', models.CharField(blank=True, choices=[('percent', 'Percentage'), ('amount', 'Fixed amount')], max_length=10)),
                ('line_discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('insurance', 'Insurance')], default='cash', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(refuse_to_drop_legacy_discounts, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='discount_reason',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale', to='billing.charge'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in customer'), ('patient', 'Registered patient')], default='walk_in', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_discounts_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage'), ('amount', 'Fixed amount')], max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('insurance', 'Insurance')], max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference',
            # Unique only once every existing row has its own (see the end).
            field=models.CharField(blank=True, editable=False, max_length=24, default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='held', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_items', to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='PosRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_note', models.TextField(blank=True)),
                ('closing_summary', models.JSONField(blank=True, default=dict)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_registers_closed', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_registers', to='inventory.stocklocation')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_registers_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.posregister'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'completed_at'], name='sales_sale_status_7ca190_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer_type', 'completed_at'], name='sales_sale_custome_61dddc_idx'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_lines', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='sales.saleline'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_returns_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_return', to='billing.refund'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.posregister'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='salereturnline',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleitem'),
        ),
        migrations.AddField(
            model_name='salereturnline',
            name='sale_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salereturn'),
        ),
        migrations.AddConstraint(
            model_name='posregister',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('opened_by',), name='one_open_pos_register_per_operator'),
        ),
        migrations.RunPython(settle_legacy_sales, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=24, unique=True),
        ),
    ]
