"""
The single-pile column goes, and a movement's location becomes required.

Both are safe only *after* 0004 has moved the quantities into
`StockRecord` rows and stamped the historical movements, which is why this
is a migration of its own rather than part of the schema change.

Written by hand rather than autogenerated: `location` is being tightened
from nullable to required, and the autodetector's answer to that is to ask
for a one-off default. There is no sensible default for "which shelf did
this happen on" — the right value was worked out per row in 0004, and this
migration only has to state that no row is null any more.
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_seed_locations_and_move_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.stocklocation",
            ),
        ),
    ]
