# Generated by Django 5.0.6 on 2026-09-11 06:40
"""
Counter identifiers and strength/form on products, the CSV stock-count import,
two movement reasons (POS sale wording, `stock_count`, `returned`) — and the
**returns quarantine** location.

The quarantine is a row, like Main Store and Pharmacy (migration 0004), and it
is neither the receiving location nor a dispensing point: medicine a customer
brings back to the POS till is received here and cannot be sold or dispensed
until somebody inspects it and either transfers it back to a shelf or counts
it out as destroyed. The seed never overwrites a location an administrator has
already created or renamed under that code.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

QUARANTINE = {
    "code": "returns-quarantine",
    "name": "Returns Quarantine",
    "kind": "store",
    "description": "Customer returns awaiting inspection. Nothing here can be sold or dispensed.",
    "is_default_receiving": False,
    "is_dispensing_point": False,
    "display_order": 90,
}


def seed_quarantine(apps, schema_editor):
    StockLocation = apps.get_model("inventory", "StockLocation")
    if not StockLocation.objects.filter(code=QUARANTINE["code"]).exists():
        StockLocation.objects.create(**QUARANTINE)


def unseed_quarantine(apps, schema_editor):
    StockLocation = apps.get_model("inventory", "StockLocation")
    StockRecord = apps.get_model("inventory", "StockRecord")
    StockMovement = apps.get_model("inventory", "StockMovement")
    location = StockLocation.objects.filter(code=QUARANTINE["code"]).first()
    if location is None:
        return
    # A quarantine that has held stock is history; leave it rather than
    # orphan the movements that point at it.
    if StockRecord.objects.filter(location=location).exists() or \
            StockMovement.objects.filter(location=location).exists():
        return
    location.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_categories_and_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='The code the POS scanner reads. Optional; unique.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g. Tablet, Syrup, Injection. Optional.', max_length=60),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock-keeping code, e.g. PH-PARA-500. Optional; unique.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500 mg, 125 mg/5 ml. Optional.', max_length=60),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('received', 'Stock received'), ('transfer_out', 'Transferred out'), ('transfer_in', 'Transferred in'), ('prescription', 'Dispensed via prescription'), ('sale', 'Sold at the pharmacy counter (POS)'), ('adjustment', 'Manual adjustment'), ('stock_count', 'Physical stock count'), ('returned', 'Customer return (quarantined)'), ('expired_writeoff', 'Expired write-off')], max_length=30),
        ),
        migrations.CreateModel(
            name='StockCountImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='previewed', max_length=12)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_imports_applied', to=settings.AUTH_USER_MODEL)),
                ('counts', models.ManyToManyField(blank=True, related_name='imports', to='inventory.stockcount')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_quarantine, unseed_quarantine),
    ]
